package sop_corba;


/**
* sop_corba/ControladorCalificacionIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

public interface ControladorCalificacionIntOperations 
{
  boolean registrarCalificacion (sop_corba.ControladorCalificacionIntPackage.CalificacionDTO objCalificacion);
  sop_corba.ControladorCalificacionIntPackage.InformeDTO obtenerAlertasVerdesCorte ();
  sop_corba.ControladorCalificacionIntPackage.InformeDTO obtenerAlertasBienestarCorte ();
  int obtenerAlertasRojas ();
} // interface ControladorCalificacionIntOperations
