package sop_corba;

/**
* sop_corba/ControladorAlertaIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

public final class ControladorAlertaIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorAlertaInt value = null;

  public ControladorAlertaIntHolder ()
  {
  }

  public ControladorAlertaIntHolder (sop_corba.ControladorAlertaInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorAlertaIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorAlertaIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorAlertaIntHelper.type ();
  }

}
