package sop_corba;

/**
* sop_corba/ControladorCalificacionIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

public final class ControladorCalificacionIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorCalificacionInt value = null;

  public ControladorCalificacionIntHolder ()
  {
  }

  public ControladorCalificacionIntHolder (sop_corba.ControladorCalificacionInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorCalificacionIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorCalificacionIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorCalificacionIntHelper.type ();
  }

}
