package sop_corba.ControladorCalificacionIntPackage;

/**
* sop_corba/ControladorCalificacionIntPackage/CalificacionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

public final class CalificacionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorCalificacionIntPackage.CalificacionDTO value = null;

  public CalificacionDTOHolder ()
  {
  }

  public CalificacionDTOHolder (sop_corba.ControladorCalificacionIntPackage.CalificacionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorCalificacionIntPackage.CalificacionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorCalificacionIntPackage.CalificacionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorCalificacionIntPackage.CalificacionDTOHelper.type ();
  }

}
