package sop_corba.ControladorCalificacionIntPackage;


/**
* sop_corba/ControladorCalificacionIntPackage/InformeDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

public final class InformeDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int corte1 = (int)0;
  public int corte2 = (int)0;
  public int corte3 = (int)0;

  public InformeDTO ()
  {
  } // ctor

  public InformeDTO (int _corte1, int _corte2, int _corte3)
  {
    corte1 = _corte1;
    corte2 = _corte2;
    corte3 = _corte3;
  } // ctor

} // class InformeDTO
