package sop_corba.ControladorCalificacionIntPackage;

/**
* sop_corba/ControladorCalificacionIntPackage/InformeDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

public final class InformeDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorCalificacionIntPackage.InformeDTO value = null;

  public InformeDTOHolder ()
  {
  }

  public InformeDTOHolder (sop_corba.ControladorCalificacionIntPackage.InformeDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorCalificacionIntPackage.InformeDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorCalificacionIntPackage.InformeDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorCalificacionIntPackage.InformeDTOHelper.type ();
  }

}
