package sop_corba.ControladorCalificacionIntPackage;


/**
* sop_corba/ControladorCalificacionIntPackage/InformeDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

abstract public class InformeDTOHelper
{
  private static String  _id = "IDL:sop_corba/ControladorCalificacionInt/InformeDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.ControladorCalificacionIntPackage.InformeDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.ControladorCalificacionIntPackage.InformeDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "corte1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "corte2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "corte3",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.ControladorCalificacionIntPackage.InformeDTOHelper.id (), "InformeDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.ControladorCalificacionIntPackage.InformeDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.ControladorCalificacionIntPackage.InformeDTO value = new sop_corba.ControladorCalificacionIntPackage.InformeDTO ();
    value.corte1 = istream.read_long ();
    value.corte2 = istream.read_long ();
    value.corte3 = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.ControladorCalificacionIntPackage.InformeDTO value)
  {
    ostream.write_long (value.corte1);
    ostream.write_long (value.corte2);
    ostream.write_long (value.corte3);
  }

}
