package sop_corba;


/**
* sop_corba/ControladorAlertaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 04:44:17 PM COT
*/

public interface ControladorAlertaIntOperations 
{
  boolean enviarAlerta (sop_corba.ControladorAlertaIntPackage.AlertaDTO objAlerta);
} // interface ControladorAlertaIntOperations
